Repository SarthakJariwala/seaborn-image, pull requests merged in 2024-09, with the labels that each got.

#733 Automatic aspect ratio calculation
  src/seaborn_image/_grid.py
  tests/test_grid.py
Labels: enhancement, python

#766 Drop support for Python 3.8
  .github/workflows/coverage.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: ci, dependencies, github_actions

#767 update version to 0.10.0 for release
  pyproject.toml
Labels: build
